### ISSUE TITLE
Slight issue with building on Ubuntu ...

### ISSUE THREAD

**Issue by RandoSY** [sayanee/palm#2]
Hi!

I started this thread here ... https://forums.adafruit.com/viewtopic.php?f=57&t=174844

I'm seeing this issue on/from my linux build of the Arduino IDE (1.8.recent)

**adafruit-nrfutil dfu genpkg --dev-type 0x0052 --sd-req 0x00B6 --application /tmp/arduino_build_72923/firmware.ino.hex /tmp/arduino_build_72923/firmware.ino.zip
Usage: adafruit-nrfutil dfu [OPTIONS] COMMAND [ARGS]...
Try 'adafruit-nrfutil dfu --help' for help**

That goes for Platform.io  as well... ???

![Screenshot from 2021-01-31 18-47-09](https://user-images.githubusercontent.com/609947/106504101-7ffa9c80-6494-11eb-9193-7727ea17e219.png)

When I run the command from the command line, it runs normally and the zip file is built.  What's with that, ??? :(

As you see on my Adafruit posting,  I was able to kludge your app on my nRF52-DK, and test, but was wondering if you'd seen this error before?

Thanks!

(I am really enjoying your postings, and learning a lot)

**Comment by RandoSY** [comment]
Here's my eventual target for all your cool tech, under 10$ US. 

https://ssihla.wordpress.com/2019/07/23/using-adafruits-bluefruit-nrf52-feather-bootloader-on-a-cheap-chineese-board/

![Screenshot_2021-02-01 Using Adafruit’s Bluefruit nRF52 Feather bootloader on a cheap chinese board ](https://user-images.githubusercontent.com/609947/106503854-2d20e500-6494-11eb-83dc-bcbd789dedd2.png)

**Comment by RandoSY** [comment]
Note I was able to do this project, (nRF52 Bluefruit Feather) piece-meal.

**"arduino-cli compile --fqbn adafruit:nrf52:feather52832 ./ -e " ...**

rasyoung@PCIeSSD:~/Desktop/Sayanee Basu/Exemplars/Get alerted on excessive UV radiation with a backpack keychain/palm-master/firmware$ arduino-cli compile --fqbn adafruit:nrf52:feather52832 ./ -e

Sketch uses 75284 bytes (25%) of program storage space. Maximum is 290816 bytes.
Global variables use 9236 bytes (17%) of dynamic memory, leaving 42988 bytes for local variables. Maximum is 52224 bytes.

1. Build HEX with arduino-cli
2. Load on nRF52-DK Jlink Drop and Add
3. Used nRFConnect to load proper Softdevice. Reboot!
4. Bingo! Check with my Nordic nrfConnect app on my smartphone.

**Comment by sayanee** [comment]
Thanks for sharing @RandoSY 😄 Did you get to resolve the error `No such command 'genpkg'`? It seems like a package from Nordic (the MCU nRF52xx).

I'll close this issue as it is not an error I can solve. But you have gone the right way by posting in on the forums. Try the Nordic forums if you have not solved it yet.

**Comment by RandoSY** [comment]
Thank you for the consideration of your prompt reply, I'll do just that. And of course, as/if I follow along your logic of reducing these builds to a simple make-file, and the appropriate support utilities to do the flashing, it can/will be a non-issue. 

I will make sure to try this on another couple of Linux instances and make sure it's not just an artifact of this new machine. (Ubuntu 20.10.recent).

Keep publishing this great content, I am enjoying, and appreciating it very much. :)

Cheers!

**Comment by sayanee** [comment]
@RandoSY Thanks 🙏🏼  I can totally understand that setting up these tools like command line and Makefiles can be a hassle, but it's a one-time setup. Happy exploring 🎈 I took some years to get it all together and even then I'm always tweaking. Find your style that you are comfortable with 😃

**Comment by sail2themoon** [comment]
Old thread, but maybe it'll help someone: I had the same error "genpkg command not found" with the latest (I guess?) version installed of adafruit-nrfutil via pip3. After I fetched the source from https://github.com/adafruit/Adafruit_nRF52_nrfutil.git everything worked.
